/** Browser checks against a fresh, fictional, real SQLite workspace. No provider key or synthetic API responses. */
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import crypto from 'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const run=process.env.DESIGN_RUN || 'final';
const out=path.join(root,'design','evidence',run);
await fs.mkdir(out,{recursive:true});
const port=4384, base=`http://127.0.0.1:${port}`;
const database=`/tmp/closetrelay-design-${Date.now()}.sqlite3`;
const python=process.env.PYTHON || '/Users/matt/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3';
const server=spawn(python,['-m','backend.server','--port',String(port),'--database',database],{cwd:root,stdio:['ignore','pipe','pipe']});
let serverLog=''; server.stdout.on('data',d=>serverLog+=d);server.stderr.on('data',d=>serverLog+=d);
const results={startedAt:new Date().toISOString(),database,base,syntheticFixtures:true,providerCalls:false,checks:[],pageErrors:[],a11y:{}};
let browser;
const check=(name,details={})=>{results.checks.push({name,status:'passed',...details});console.log(`PASS ${name}`)};
const save=async(name,data)=>fs.writeFile(path.join(out,name),JSON.stringify(data,null,2)+'\n');
const shot=async(page,name,fullPage=false)=>page.screenshot({path:path.join(out,`${name}.png`),fullPage,animations:'disabled'});
const stateOf=async page=>page.evaluate(async()=>{const r=await fetch('/api/state',{cache:'no-store'});return r.json()});
const settled=async page=>page.waitForFunction(()=>!document.querySelector('#loading')||document.querySelector('#loading').hidden);
const clickAction=async(page,action)=>{await page.locator(`[data-action="${action}"]`).click();};
async function axe(page,label){
  // Execute only the local audit library through the browser debugger; the app's CSP remains intact.
  await page.evaluate(await fs.readFile(process.env.AXE_PATH || '/tmp/closetrelay-design-axe-4.12.1.min.js','utf8'));
  const report=await page.evaluate(async()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}));
  await save(`a11y-${label}.json`,report);
  results.a11y[label]={violations:report.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.length})),incomplete:report.incomplete.map(v=>v.id)};
}
try{
  for(let i=0;i<50;i++){try{if((await fetch(`${base}/api/state`)).ok)break;}catch{}await new Promise(r=>setTimeout(r,150));if(i===49)throw new Error('QA server did not start');}
  browser=await chromium.launch({headless:true});
  const ctx=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});
  const a=await ctx.newPage(); const b=await ctx.newPage();
  for(const p of[a,b])p.on('pageerror',e=>results.pageErrors.push(e.message));
  await a.goto(base);await settled(a);await a.locator('#items [data-item]').first().waitFor();await a.evaluate(()=>document.fonts.ready);
  assert.equal(await a.locator('[data-item]').count(),4);
  assert.equal(await a.locator('#appointment-name').innerText(),'Appointment A');
  assert.equal(await a.locator('[data-action="preview"]').isDisabled(),true);
  assert.equal(await a.evaluate(()=>document.documentElement.scrollWidth),1440);
  await shot(a,'desktop-initial'); await axe(a,'desktop');
  check('Desktop real-data load, no-key preview, no horizontal overflow');
  await a.locator('#item-search').fill('NO-MATCH-INVENTED');
  assert.equal(await a.locator('[data-item]').count(),0);await a.getByRole('button',{name:'Show all items',exact:true}).click();
  assert.equal(await a.locator('[data-item]').count(),4);assert.equal(await a.locator('#item-search').inputValue(),'');
  check('Search empty-state recovery preserves the selected garment');
  const keyboardPage=await ctx.newPage();keyboardPage.on('pageerror',e=>results.pageErrors.push(e.message));await keyboardPage.goto(base);await settled(keyboardPage);
  await keyboardPage.keyboard.press('Tab');
  assert.equal(await keyboardPage.evaluate(()=>document.activeElement.textContent.trim()),'Skip to appointment');await keyboardPage.keyboard.press('Enter');
  assert.equal(await keyboardPage.evaluate(()=>document.activeElement.id),'main');
  await keyboardPage.getByRole('button',{name:'Add appointment',exact:true}).click();await keyboardPage.locator('#new-name').waitFor();
  assert.equal(await keyboardPage.locator('#form-dialog').evaluate(el=>el.open),true);await keyboardPage.keyboard.press('Escape');
  assert.equal(await keyboardPage.locator('#form-dialog').evaluate(el=>el.open),false);
  assert.equal(await keyboardPage.evaluate(()=>document.activeElement.id),'add-appointment');await keyboardPage.close();
  check('Keyboard skip link and native dialog Escape restore focus');
  await b.goto(base);await settled(b);await b.getByRole('button',{name:/Fictional appointment B/}).click();
  await b.getByRole('button',{name:'View Sample navy jacket, DEMO-JKT-01, Available',exact:true}).click();
  await clickAction(b,'approve');await b.locator('[data-action="hold"]').waitFor();
  await clickAction(a,'approve');await a.locator('[data-action="hold"]').waitFor();
  assert.equal(await a.evaluate(()=>document.activeElement.dataset.action),'hold');
  await a.keyboard.press('Enter');await a.locator('#scan-id').waitFor();
  assert.equal(await a.evaluate(()=>document.activeElement.id),'scan-id');
  await clickAction(b,'hold');await b.locator('#message.error').waitFor();
  const conflict=await b.locator('#message').innerText();await fs.writeFile(path.join(out,'stale-hold-response.txt'),conflict);
  const held=await stateOf(a);assert.equal(held.items.find(i=>i.id==='DEMO-JKT-01').owner,'demo-appointment-a');
  assert.equal(held.appointments.find(p=>p.id==='demo-appointment-b').active_holds.length,0);
  check('Two real windows: stale competing hold is refused, A retains the item');
  const stale=await ctx.newPage();stale.on('pageerror',e=>results.pageErrors.push(e.message));await stale.goto(base);await settled(stale);await stale.locator('#scan-id').waitFor();
  await clickAction(a,'edit-item');await a.locator('#edit-condition').fill('Invented QA condition: small mark on left cuff; review this change before packing.');
  await a.getByRole('button',{name:'Save & require fresh approval',exact:true}).click();
  await a.getByText('This item changed. Review it again.',{exact:true}).waitFor();
  assert.equal(await a.locator('#scan-id').count(),0);
  let data=await stateOf(a), item=data.items.find(i=>i.id==='DEMO-JKT-01'), ap=data.appointments.find(p=>p.id==='demo-appointment-a');
  assert.equal(item.version,2);assert.equal(item.state,'available');assert.notEqual(ap.approval.state,'active');assert.equal(ap.active_holds.length,0);
  await a.locator('#choice-panel').scrollIntoViewIfNeeded();await shot(a,'changed-condition');
  check('Condition revision invalidates the real old approval and hold; packing disappears',{version:item.version});
  await stale.locator('#scan-id').fill('DEMO-JKT-01');await stale.getByRole('button',{name:'Confirm exact item & pack',exact:true}).click();await stale.locator('#message.error').waitFor();
  assert.equal(await stale.locator('#scan-id').count(),0);
  const staleMessage=await stale.locator('#message').innerText();await fs.writeFile(path.join(out,'stale-packing-response.txt'),staleMessage);
  assert.ok(!staleMessage.includes('Review the item ID in the packing form.'),'A removed stale packing form must not be offered as recovery.');
  assert.ok(staleMessage.includes('Hold or approval changed; packing requires current client approval'));await stale.close();
  check('A second window cannot pack a revoked hold; recovery names the real stale-hold failure');
  await clickAction(a,'approve');await a.locator('[data-action="hold"]').waitFor();await clickAction(a,'hold');await a.locator('#scan-id').waitFor();
  await a.setViewportSize({width:1280,height:720});
  await a.locator('#scan-id').fill('DEMO-JKT-02');await a.getByRole('button',{name:'Confirm exact item & pack',exact:true}).click();
  await a.locator('#pack-error').waitFor();
  assert.equal(await a.locator('#scan-id').inputValue(),'DEMO-JKT-02');assert.equal(await a.locator('#scan-id').getAttribute('aria-invalid'),'true');
  assert.equal(await a.evaluate(()=>document.activeElement.id),'scan-id');
  data=await stateOf(a);ap=data.appointments.find(p=>p.id==='demo-appointment-a');assert.equal(ap.handoffs.length,0);assert.equal(ap.active_holds.length,1);
  const wrongError=await a.locator('#pack-error').innerText();await fs.writeFile(path.join(out,'wrong-item-response.txt'),wrongError);await shot(a,'wrong-item-desktop');
  results.packingBounds=await a.evaluate(()=>Object.fromEntries(['.condition-note','#scan-id','#scan-help','#pack-error'].map(s=>{const r=document.querySelector(s).getBoundingClientRect();return[s,{top:r.top,bottom:r.bottom,width:r.width}]})));
  assert.ok(results.packingBounds['.condition-note'].top>=0 && results.packingBounds['#pack-error'].bottom<=720,'Condition and inline packing error must be visible together at 1280×720.');
  results.criticalText=await a.evaluate(()=>Object.fromEntries(['.chosen-item p','.detail-list','.condition-note','.button-primary'].map(s=>[s,getComputedStyle(document.querySelector(s)).fontSize])));
  assert.ok(Object.values(results.criticalText).every(v=>parseFloat(v)>=14),'Critical decision text must be at least 14px.');
  await a.setViewportSize({width:390,height:844});
  await a.evaluate(()=>window.scrollTo(0,0));await a.locator('[data-action="show-choice"]').click();await a.locator('#scan-id').focus();await a.locator('#scan-id').evaluate(el=>el.scrollIntoView({block:'center'}));
  assert.equal(await a.evaluate(()=>document.documentElement.scrollWidth),390);await shot(a,'wrong-item-mobile');await axe(a,'mobile-error');
  check('Wrong-item refusal is inline, retains typed ID, preserves hold, focuses correction; desktop and phone');
  await a.locator('#scan-id').fill('DEMO-JKT-01');await a.locator('#scan-id').press('Enter');
  await a.getByRole('heading',{name:'The right item, packed.',exact:true}).waitFor();
  data=await stateOf(a);ap=data.appointments.find(p=>p.id==='demo-appointment-a');assert.equal(ap.handoffs.length,1);assert.equal(ap.handoffs[0].item_id,'DEMO-JKT-01');assert.equal(ap.handoffs[0].item_version,2);
  await a.reload();await settled(a);await a.getByRole('heading',{name:'The right item, packed.',exact:true}).waitFor();
  await a.evaluate(()=>window.scrollTo(0,0));await a.locator('[data-action="show-choice"]').click();await shot(a,'mobile-packed');
  await clickAction(a,'manifest');await a.locator('#record-dialog').waitFor();assert.match(await a.locator('#record-content').innerText(),/DEMO-JKT-01/);
  await shot(a,'mobile-packing-record');await a.keyboard.press('Escape');
  check('Correct ID packs exactly one version-2 handoff and survives reload; saved record is readable at 390px');
  await a.locator('[data-action="configure-provider"]').click();assert.equal(await a.locator('#provider-key').getAttribute('type'),'password');assert.equal(await a.locator('#provider-key').inputValue(),'');
  assert.deepEqual(await a.evaluate(()=>({local:Object.keys(localStorage),session:Object.keys(sessionStorage)})),{local:[],session:[]});await a.keyboard.press('Escape');
  await a.getByText('Why is the preview unavailable?',{exact:true}).click();assert.match(await a.locator('.preview-details').innerText(),/without a preview/);assert.equal(await a.locator('[data-action="preview"]').isDisabled(),true);
  check('Provider remains truthfully unavailable; password field empty, browser storage empty, no call made');
  await a.setViewportSize({width:1440,height:1000});await a.getByRole('button',{name:/Fictional appointment B/}).click();
  await a.getByRole('button',{name:'View Sample navy jacket, DEMO-JKT-01, Packed',exact:true}).click();
  assert.equal(await a.locator('[data-action="approve"]').isDisabled(),true);await shot(a,'packed-item-unavailable-elsewhere');
  await a.locator('#item-search').fill('DEMO-JKT-03');await a.locator('[data-item="DEMO-JKT-03"]').click();await a.locator('#item-search').fill('');
  await a.evaluate(()=>window.scrollTo(0,0));await shot(a,'desktop-final');
  await a.setViewportSize({width:390,height:844});await a.evaluate(()=>window.scrollTo(0,0));await shot(a,'mobile-final');await axe(a,'mobile');
  await a.locator('[data-action="show-choice"]').click();assert.equal(await a.evaluate(()=>document.activeElement.id),'choice-heading');await a.waitForFunction(()=>getComputedStyle(document.querySelector('#mobile-selection')).display==='none');await shot(a,'mobile-choice');
  check('Packed garment cannot be approved elsewhere; mobile review jump focuses the selected item');
  assert.deepEqual(results.pageErrors,[]);
  check('No uncaught browser JavaScript errors during the full workflow');
  const violations=Object.entries(results.a11y).filter(([,v])=>v.violations.length);
  if(violations.length)throw new Error(`Automated accessibility violations: ${JSON.stringify(violations)}`);
  check('Axe WCAG-tagged desktop, phone, and phone-error scans contain zero violations (not full conformance certification)');
  await save('final-server-state.json',await stateOf(a));
  results.status='passed';
}catch(error){results.status='failed';results.error={message:error.message,stack:error.stack};console.error(error);if(browser){const pages=browser.contexts().flatMap(c=>c.pages());for(let i=0;i<pages.length;i++)try{await shot(pages[i],`failure-page-${i}`)}catch{}}process.exitCode=1;}
finally{
  results.finishedAt=new Date().toISOString();results.sources={};
  for(const file of ['ui/index.html','ui/styles.css','ui/app.js','design/verify-ui.mjs'])results.sources[file]=crypto.createHash('sha256').update(await fs.readFile(path.join(root,file))).digest('hex');
  await save('results.json',results);await fs.writeFile(path.join(out,'server.log'),serverLog);await browser?.close();server.kill('SIGTERM');
}
