const dialog=document.createElement('dialog');dialog.id='try-on-dialog';dialog.setAttribute('aria-labelledby','try-on-title');
dialog.innerHTML=`<div class="dialog-top"><span class="eyebrow">REAL YOUCAM · FICTIONAL INPUTS</span><button type="button" class="icon-button" id="try-on-close" aria-label="Close virtual try-on">×</button></div><h2 id="try-on-title">Try the sample navy blazer</h2><p class="try-on-intro">YouCam places this sample blazer on our fictional adult. This demo accepts no personal photos. The result shows appearance, not fit or garment condition.</p><div class="try-on-inputs"><figure><img src="/demo/synthetic-adult.png" alt="AI-generated fictional adult before virtual try-on"><figcaption>Fictional adult · source image</figcaption></figure><figure><img src="/demo/synthetic-navy-blazer.png" alt="AI-generated sample navy blazer provided to YouCam"><figcaption>Sample navy blazer · reference</figcaption></figure><figure class="try-on-output" id="try-on-output"><div class="preview-pending">Your YouCam result will appear here.</div><figcaption>Actual provider result</figcaption></figure></div><p id="try-on-status" role="status" aria-live="polite"></p><div class="try-on-actions"><button type="button" class="button button-primary" id="try-on-generate" disabled>Generate with YouCam</button><button type="button" class="button button-quiet" id="try-on-refresh">Check status</button></div><p class="compact-note">One shared sample request uses the free trial. Later visits display its saved result without another generation. This sample does not preview other garments in the rack.</p><details class="inspect-details"><summary>View generation evidence</summary><pre id="try-on-evidence">No provider request yet.</pre></details>`;
document.body.append(dialog);
let current=null,timer=null,requesting=false,opener=null,lastError='';
const $=id=>dialog.querySelector(id);
function explanation(){
  if(!current)return '<strong>Virtual try-on:</strong> Check the sample fitting demo.';
  if(!current.configured)return '<strong>Virtual try-on is not connected.</strong> Choosing, reserving and packing still work.';
  if(current.status==='succeeded')return '<strong>Virtual try-on is ready.</strong> View the saved YouCam result for our fictional adult and navy blazer.';
  if(['failed','creation_uncertain'].includes(current.status))return '<strong>Virtual try-on needs attention.</strong> Open the demo to inspect the actual provider status.';
  return '<strong>Try virtual fitting.</strong> YouCam can place the sample navy blazer on our fictional adult.';
}
globalThis.renderSampleCapability=()=>{
  const box=document.querySelector('#preview-capability');if(box)box.innerHTML=`${explanation()} <button type="button" class="button button-quiet" data-action="sample-preview">Open try-on demo</button>`;
};
function render(){
  globalThis.renderSampleCapability();if(!current){$('#try-on-status').textContent=lastError||'Checking the provider record…';return;}
  const status=current.status;
  $('#try-on-generate').disabled=!current.configured||status!=='ready'||requesting;
  $('#try-on-generate').hidden=status==='succeeded';
  $('#try-on-refresh').disabled=requesting;
  $('#try-on-status').textContent=!current.configured?'The service is not connected yet. No result has been generated.':{
    ready:'Ready to send the two fictional images to YouCam.',creating:'Sending the fictional sample to YouCam…',processing:'YouCam is generating the sample. This view checks its status automatically.',
    succeeded:`Saved result from a real YouCam request, started ${new Date(current.created_at).toLocaleString()}. No new request was made by opening this view.`,
    failed:`YouCam did not produce a usable result (${current.error}). No replacement image is shown.`,
    creation_uncertain:'The generation confirmation was lost. It may have reached YouCam. Automatic retry is stopped to avoid spending credits twice.'
  }[status]??'Checking the provider record…';
  if(lastError)$('#try-on-status').textContent=lastError;
  $('#try-on-evidence').textContent=JSON.stringify(current,null,2);
  if(status==='succeeded'&&current.result_url==='/api/sample-preview/image'){
    if(!$('#try-on-result')){
      const image=new Image();image.id='try-on-result';image.alt='Actual YouCam Clothes V4 output: fictional adult wearing the sample navy blazer';
      image.onload=()=>{$('#try-on-output').replaceChildren(image,Object.assign(document.createElement('figcaption'),{textContent:'Generated by YouCam · saved sample'}));};
      image.onerror=()=>{$('#try-on-status').textContent='YouCam completed, but the result image could not load. Check status to retry.';};image.src=current.result_url;
    }
  }
}
async function refresh(start=false){
  if(requesting)return;requesting=true;render();
  try{
    const response=await fetch('/api/sample-preview',{method:start?'POST':'GET',headers:start?{'Content-Type':'application/json'}:undefined,body:start?JSON.stringify({fixture:'navy-adult-v1'}):undefined,cache:'no-store',signal:AbortSignal.timeout(30000)});
    const result=await response.json();if(!response.ok)throw new Error(result.error?.message??'The provider record could not load.');current=result;lastError='';render();
  }catch(error){lastError=error.message;}
  finally{requesting=false;render();clearTimeout(timer);if(dialog.open&&['creating','processing'].includes(current?.status))timer=setTimeout(()=>refresh(),3500);}
}
document.addEventListener('click',event=>{const target=event.target.closest('[data-action="sample-preview"]');if(!target)return;opener=target;dialog.showModal();refresh();});
$('#try-on-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{clearTimeout(timer);const target=opener?.isConnected?opener:document.querySelector('[data-action="sample-preview"]');target?.focus({preventScroll:true});});
$('#try-on-generate').addEventListener('click',()=>refresh(true));$('#try-on-refresh').addEventListener('click',()=>refresh());
void refresh();
